# Amazon CodeDeploy app spec

os: linux
# amazon requires this be specified and set to 0.0 or the whole Enterprise comes apart, which makes Captain Kirk unhappy
version: 0.0

files:
  - source: analyst-stats.jar
    destination: /opt

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user
      timeout: 60

  ApplicationStop:
    - location: scripts/stop.sh
      runas: ec2-user
      timeout: 60
